/**
 * Shared SVG primitives for the profile design system.
 *
 * Everything rendered into assets/ goes through here so that the grid, type
 * scale, radii, motion vocabulary and palette are applied identically across
 * every asset. Nothing in this file reaches the network at render time - font
 * subsets and icon paths are resolved beforehand by tools/fetch-fonts.mjs and
 * tools/fetch-icons.mjs and read from tools/lib/embedded.json.
 */

import { readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
export const ROOT = join(here, '..', '..')

export const tokens = JSON.parse(
  readFileSync(join(ROOT, 'tools', 'design-tokens.json'), 'utf8'),
)

/** Simple Icons paths, generated by tools/fetch-icons.mjs and committed. */
export const icons = existsSync(join(here, 'icons.json'))
  ? JSON.parse(readFileSync(join(here, 'icons.json'), 'utf8'))
  : {}

// ---------------------------------------------------------------------------
// text helpers
// ---------------------------------------------------------------------------

export const esc = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

export const schemeOf = (s) => tokens.schemes[s]

// ---------------------------------------------------------------------------
// typography
// ---------------------------------------------------------------------------

export const display = (size, weight = 700) =>
  `${weight} ${size}px '${tokens.type.display.family}', ${tokens.type.bodyStack}`
export const mono = (size, weight = 500) =>
  `${weight} ${size}px '${tokens.type.mono.family}', ${tokens.type.monoStack}`
export const body = (size, weight = 400) =>
  `${weight} ${size}px ${tokens.type.bodyStack}`

/** A <text> node with the project's typographic defaults applied. */
export function text(x, y, str, opts = {}) {
  const {
    size = tokens.type.scale.body,
    family = 'body',
    weight = 400,
    fill = 'text',
    anchor = 'start',
    tracking = 0,
    tabular = false,
    opacity,
    extra = '',
  } = opts
  const font = family === 'display' ? display(size, weight)
    : family === 'mono' ? mono(size, weight)
    : body(size, weight)
  const attrs = [
    `x="${x}"`, `y="${y}"`,
    `font-family="${esc(font)}"`,
    `font-size="${size}"`,
    `fill="${fill}"`,
  ]
  // text() owns typography. Letting a caller also pass font-family through
  // `extra` produces a duplicate attribute, which makes the whole SVG invalid
  // XML and the asset silently fails to render. Fail loudly instead.
  if (/font-family/.test(extra)) {
    throw new Error('text(): use family/size/weight, not extra font-family (duplicate attribute)')
  }
  if (weight !== 400) attrs.push(`font-weight="${weight}"`)
  if (anchor !== 'start') attrs.push(`text-anchor="${anchor}"`)
  if (tracking) attrs.push(`letter-spacing="${tracking}"`)
  if (opacity !== undefined) attrs.push(`opacity="${opacity}"`)
  if (tabular) attrs.push('style="font-variant-numeric:tabular-nums"')
  if (extra) attrs.push(extra)
  return `<text ${attrs.join(' ')}>${esc(str)}</text>`
}

// ---------------------------------------------------------------------------
// colour
// ---------------------------------------------------------------------------

export const accent = (s, name) => schemeOf(s).brand[name]

/**
 * Greedy word wrap for SVG text, which has no automatic wrapping.
 *
 * Character width is approximated per family rather than measured, because
 * measurement needs a layout engine. The ratios are tuned so the estimate errs
 * slightly wide, which is the safe direction: a line that looks short rather
 * than one that silently overruns the card.
 */
export function wrapText(str, maxWidth, { size = 12, ratio = 0.53, maxLines = 99 } = {}) {
  const perLine = Math.max(8, Math.floor(maxWidth / (size * ratio)))
  const words = String(str).split(/\s+/)
  const lines = []
  let line = ''
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word
    if (candidate.length > perLine && line) {
      lines.push(line)
      line = word
    } else {
      line = candidate
    }
  }
  if (line) lines.push(line)
  if (lines.length > maxLines) {
    const kept = lines.slice(0, maxLines)
    kept[maxLines - 1] = kept[maxLines - 1].replace(/.{0,3}$/, '') + '…'
    return kept
  }
  return lines
}

// ---------------------------------------------------------------------------
// document assembly
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// shared graphic components
// ---------------------------------------------------------------------------

/** Rounded surface used by every card in the system. */
export function panel(x, y, w, h, s, { radius = tokens.radius.card, fill, stroke, shadow = true, delay = '' } = {}) {
  const sc = schemeOf(s)
  return `<g${delay ? ` class="rise ${delay}"` : ''}>
${shadow ? `<rect x="${x}" y="${y + 3}" width="${w}" height="${h}" rx="${radius}" fill="#000" opacity="${s === 'dark' ? '.34' : '.07'}"/>` : ''}
<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${radius}" fill="${fill ?? sc.surface}" stroke="${stroke ?? sc.border}" stroke-width="1"/>
</g>`
}

/** Pill-shaped chip with a centred label. Returns the markup plus its width. */
export function chip(x, y, label, s, { accent: ac, size = tokens.type.scale.micro, padX = 10, h = 22, stroke } = {}) {
  const sc = schemeOf(s)
  const w = Math.round(label.length * size * 0.62 + padX * 2)
  const color = ac ? accent(s, ac) : sc.textMuted
  return {
    w,
    markup: `<g><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${tokens.radius.chip}" fill="${color}" fill-opacity="${s === 'dark' ? '.13' : '.1'}" stroke="${stroke ?? color}" stroke-opacity=".32"/>` +
      text(x + w / 2, y + h / 2 + size * 0.36, label, {
        size, family: 'mono', weight: 500, fill: color, anchor: 'middle',
      }) + `</g>`,
  }
}

/** Breathing status dot. */
export function statusDot(cx, cy, s, r = 4) {
  const sc = schemeOf(s)
  const c = sc.brand.teal
  return `<g><circle cx="${cx}" cy="${cy}" r="${r + 5}" fill="${c}" opacity=".18" class="breathe" style="transform-origin:${cx}px ${cy}px"/><circle cx="${cx}" cy="${cy}" r="${r}" fill="${c}"/></g>`
}

/**
 * Ambient dot grid. Emitted as a <pattern> rather than one circle per cell:
 * a 1200x424 field is ~800 elements inline, which is ~32 KB of markup, versus
 * a single rect here.
 */
export function dotField(id, s, step = 26, r = 1) {
  const sc = schemeOf(s)
  return `<pattern id="${id}" width="${step}" height="${step}" patternUnits="userSpaceOnUse"><circle cx="${r}" cy="${r}" r="${r}" fill="${sc.gridDot}"/></pattern>`
}

export const dotFill = (x, y, w, h, id, opacity = 1) =>
  `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="url(#${id})" opacity="${opacity}"/>`

/** Grain overlay. Flat gradients band badly on large areas; this dithers them. */
export function grain(s) {
  const sc = schemeOf(s)
  return `<rect width="100%" height="100%" filter="url(#grainF)" opacity="${sc.grain}" style="mix-blend-mode:overlay"/>`
}

// ---------------------------------------------------------------------------
// contrast gate
// ---------------------------------------------------------------------------

const srgb = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)

export function luminance(hex) {
  let h = hex.replace('#', '')
  if (h.length === 3) h = h.split('').map((c) => c + c).join('')
  const [r, g, b] = [0, 2, 4].map((i) => srgb(parseInt(h.slice(i, i + 2), 16) / 255))
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

export function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

export const aa = (a, b, large = false) => contrast(a, b) >= (large ? 3 : 4.5)
